version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=careflow;Username=postgres;Password=postgres
    ports:
      - "5000:8080"
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: careflow
    ports:
      - "5499:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
