version: "3.8"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: careflow
    ports:
      - "5499:5499"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
